import {
  SiApple,
  SiGoogle,
  SiDogecoin,
  SiMeta,
  SiTesla,
  SiNvidia,
  SiSamsung,
  SiNetflix,
  SiBitcoin,
  SiSpotify,
  SiUber,
  SiAirbnb,
  SiShopify,
  SiPaypal,
  SiLitecoin,
  SiIntel,
  SiAmd,
  SiSalesforce,
  SiVisa,
  SiMonero,
  SiMastercard,
  SiCisco,
  SiEthereum,
  SiRipple,
  SiSolana,
  SiPolkadot,
  SiCardano,
  SiBinance,
  SiChainlink,
} from "react-icons/si";
import { FaAmazon } from "react-icons/fa";
import { BiLogoAdobe } from "react-icons/bi";
import { BsMicrosoft } from "react-icons/bs";
import { RiTwitterXFill } from "react-icons/ri";

// `symbol`/`type` connect each logo to real data elsewhere in the app
// (search, watchlist, /stock/[symbol]). `href` is omitted for entries with
// no working ticker — X/Twitter has been private and delisted since 2022,
// Samsung trades only on the Korean exchange (unsupported by Finnhub's
// free/US-focused quote endpoint), and Monero was delisted from Binance in
// 2024, breaking the BINANCE:{ticker}USDT pattern the crypto route uses.
// Those three stay in the strip for visual variety but aren't clickable.
export const companies = [
  {
    node: <SiBitcoin className="text-[#F7931A] w-8 h-8" />,
    title: "Bitcoin",
    symbol: "BTC",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <SiPolkadot className="text-[#E6007A] w-8 h-8" />,
    title: "Polkadot",
    symbol: "DOT",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <SiApple className="text-white w-8 h-8" />,
    title: "Apple",
    symbol: "AAPL",
    type: "stock",
    href: "/stock/AAPL",
  },
  {
    node: <BsMicrosoft className="text-[#00A4EF] w-8 h-8" />,
    title: "Microsoft",
    symbol: "MSFT",
    type: "stock",
    href: "/stock/MSFT",
  },
  {
    node: <SiGoogle className="text-[#4285F4] w-8 h-8" />,
    title: "Google",
    symbol: "GOOGL",
    type: "stock",
    href: "/stock/GOOGL",
  },
  {
    node: <SiRipple className="text-[#346AA9] w-8 h-8" />,
    title: "XRP",
    symbol: "XRP",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <FaAmazon className="text-[#FF9900] w-8 h-8" />,
    title: "Amazon",
    symbol: "AMZN",
    type: "stock",
    href: "/stock/AMZN",
  },
  {
    node: <SiMeta className="text-[#0082FB] w-8 h-8" />,
    title: "Meta",
    symbol: "META",
    type: "stock",
    href: "/stock/META",
  },
  {
    node: <SiTesla className="text-[#E82127] w-8 h-8" />,
    title: "Tesla",
    symbol: "TSLA",
    type: "stock",
    href: "/stock/TSLA",
  },
  {
    node: <SiNvidia className="text-[#76B900] w-8 h-8" />,
    title: "NVIDIA",
    symbol: "NVDA",
    type: "stock",
    href: "/stock/NVDA",
  },
  {
    node: <SiSolana className="text-[#9945FF] w-8 h-8" />,
    title: "Solana",
    symbol: "SOL",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <SiDogecoin className="text-[#C2A633] w-8 h-8" />,
    title: "Dogecoin",
    symbol: "DOGE",
    type: "crypto",
    href: "/crypto",
  },
  // No working ticker: Samsung trades on the Korean exchange only.
  { node: <SiSamsung className="text-[#1428A0] w-8 h-8" />, title: "Samsung" },
  {
    node: <SiNetflix className="text-[#E50914] w-8 h-8" />,
    title: "Netflix",
    symbol: "NFLX",
    type: "stock",
    href: "/stock/NFLX",
  },
  {
    node: <SiPaypal className="text-[#009CDE] w-8 h-8" />,
    title: "PayPal",
    symbol: "PYPL",
    type: "stock",
    href: "/stock/PYPL",
  },
  {
    node: <SiSpotify className="text-[#1DB954] w-8 h-8" />,
    title: "Spotify",
    symbol: "SPOT",
    type: "stock",
    href: "/stock/SPOT",
  },
  {
    node: <SiUber className="text-white w-8 h-8" />,
    title: "Uber",
    symbol: "UBER",
    type: "stock",
    href: "/stock/UBER",
  },
  {
    node: <SiAirbnb className="text-[#FF5A5F] w-8 h-8" />,
    title: "Airbnb",
    symbol: "ABNB",
    type: "stock",
    href: "/stock/ABNB",
  },
  {
    node: <SiIntel className="text-[#0071C5] w-8 h-8" />,
    title: "Intel",
    symbol: "INTC",
    type: "stock",
    href: "/stock/INTC",
  },
  {
    node: <SiShopify className="text-[#96BF48] w-8 h-8" />,
    title: "Shopify",
    symbol: "SHOP",
    type: "stock",
    href: "/stock/SHOP",
  },
  {
    node: <SiEthereum className="text-[#627EEA] w-8 h-8" />,
    title: "Ethereum",
    symbol: "ETH",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <SiAmd className="text-[#ED1C24] w-8 h-8" />,
    title: "AMD",
    symbol: "AMD",
    type: "stock",
    href: "/stock/AMD",
  },
  {
    node: <SiSalesforce className="text-[#00A1E0] w-8 h-8" />,
    title: "Salesforce",
    symbol: "CRM",
    type: "stock",
    href: "/stock/CRM",
  },
  {
    node: <BiLogoAdobe className="text-[#FF0000] w-8 h-8" />,
    title: "Adobe",
    symbol: "ADBE",
    type: "stock",
    href: "/stock/ADBE",
  },
  // No working ticker: X/Twitter has been private and delisted since 2022.
  { node: <RiTwitterXFill className="text-white w-8 h-8" />, title: "X" },
  {
    node: <SiVisa className="text-[#1A1F71] w-8 h-8" />,
    title: "Visa",
    symbol: "V",
    type: "stock",
    href: "/stock/V",
  },
  {
    node: <SiMastercard className="text-[#EB001B] w-8 h-8" />,
    title: "Mastercard",
    symbol: "MA",
    type: "stock",
    href: "/stock/MA",
  },
  {
    node: <SiCisco className="text-[#1BA0D7] w-8 h-8" />,
    title: "Cisco",
    symbol: "CSCO",
    type: "stock",
    href: "/stock/CSCO",
  },
  {
    node: <SiBinance className="text-[#F3BA2F] w-8 h-8" />,
    title: "BNB",
    symbol: "BNB",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <SiCardano className="text-[#0033AD] w-8 h-8" />,
    title: "Cardano",
    symbol: "ADA",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <SiChainlink className="text-[#2A5ADA] w-8 h-8" />,
    title: "Chainlink",
    symbol: "LINK",
    type: "crypto",
    href: "/crypto",
  },
  {
    node: <SiLitecoin className="text-[#BFBBBB] w-8 h-8" />,
    title: "Litecoin",
    symbol: "LTC",
    type: "crypto",
    href: "/crypto",
  },
  // No working ticker: Monero was delisted from Binance in 2024.
  { node: <SiMonero className="text-[#FF6600] w-8 h-8" />, title: "Monero" },
];
